### ISSUE TITLE
Removing cookies throws an error

### ISSUE THREAD

**Issue by riasvdv** [nystudio107/craft3-cookies#1]
When removing a cookie, Craft throws the following error

<img width="834" alt="afbeelding" src="https://user-images.githubusercontent.com/3626559/35194825-f6e603be-feb9-11e7-8449-638dbeba299a.png">

When checking if you have to remove the cookie, there's the following code:

```php
if ($name == "") {
    Craft::$app->request->cookies->remove($name);
}
``` 

Shouldn't this be `if ($value == "")`?

But if I change that the following error is thrown:

<img width="816" alt="afbeelding" src="https://user-images.githubusercontent.com/3626559/35194845-4a682bfc-feba-11e7-8acf-e99893761dfa.png">

If I change the whole statement to this:

```php
if ($value == "") {
    Craft::$app->request->cookies->readOnly = false;
    Craft::$app->request->cookies->remove($name);
    Craft::$app->request->cookies->readOnly = true;
}
```

It works, but that seems a bit convulted somehow?

**Comment by riasvdv** [comment]
Ah, dove into Yii2 and it seems that when you remove cookies, you have to do it from the `response` class and not the `request`, so like this:

`Craft::$app->response->cookies->remove($name);`

**Comment by riasvdv** [comment]
Created a PR #2 that should fix everything :)

**Comment by khalwat** [comment]
Thanks @Rias500 !

**Comment by khalwat** [comment]
I've also added try/catch so errors are logged instead of exceptions thrown

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft3-cookies/releases/tag/1.1.8
