### ISSUE TITLE
Cookies are always forced to 'secure'

### ISSUE THREAD

**Issue by jedimonkey** [nystudio107/craft3-cookies#11]
Looks like when some changes were made 2 months ago to handle php7's setcookie parameter changes, secure was set to true and can't be changed.

https://github.com/nystudio107/craft-cookies/blob/v1/src/services/CookiesService.php#L62

Can this be fixed to be configurable?

**Comment by jedimonkey** [comment]
PR for this issue https://github.com/nystudio107/craft-cookies/pull/12

**Comment by jedimonkey** [comment]
... is it possible to merge my PR?

**Comment by martijnckx** [comment]
I have the same issue, and this PR fixes it! Please merge #12 .

**Comment by jsunsawyer** [comment]
Just go stuck on this myself. Plugin doesn't work using non secure cookies.

**Comment by jamiematrix** [comment]
@jsunsawyer Same for me - had been struggling to use the plugin until I found this issue. Making the change manually makes it work for now.

**Comment by goraxan** [comment]
Same problem here. I can't use this plugin locally since I'm using http in my dev machine.

@khalwat is this intentional? Is there any reason why #12 can't be merged?

Thanks

**Comment by khalwat** [comment]
Sure... sorry about that, I'll merge it in.

I think part of the reason is Craft's new default setting to to enable secure cookies by default if the protocol is https:

https://craftcms.com/docs/3.x/config/config-settings.html#usesecurecookies

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-cookies/releases/tag/1.1.13
