### ISSUE TITLE
Documentation: same example added twice in a row

### ISSUE THREAD

**Issue by craftedsystems** [nystudio107/craft3-cookies#23]
### Describe the bug
The _Retrieving Secure cookies_ example is listed twice.

### To reproduce
see [retrieving-secure-cookies](https://github.com/nystudio107/craft-cookies/blob/v1/docs/docs/README.md#retrieving-secure-cookies)

Sorry, Andrew, it's not a bug, but I can't change the label. :)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-cookies/commit/fddc8712b946612c36daf73a2004b81396d82792
