### ISSUE TITLE
Settings page blank

### ISSUE THREAD

**Issue by proimage** [nystudio107/craft3-cookies#26]
### Describe the bug
The settings panel of the plugin is blank.

(This is more of an aside, but might be related) This is after I attempted to install the plugin via the Craft Store onto a site running on Craft Nitro 2 under WSL2. When I did so, it claimed the plugin was installed, but a problem happened that prevented it from being enabled. Craft then asked me if I wanted to uninstall it or continue as-is. I then successfully installed and enabled the plugin via the command line (`$ nitro composer require nystudio107/craft-cookies` and then `$ nitro craft plugin/install cookies`).

### To reproduce
Steps to reproduce the behaviour:
1. Go to the control panel
2. Click on Settings
3. Click on the Cookies plugin down below to jump right to the plugin's settings panel
3. Settings panel is blank.

### Expected behaviour
I expected the settings panel would have a _raison d'être_, but alas... 

### Screenshots
![image](https://user-images.githubusercontent.com/1027523/119987008-372f9c00-bfcd-11eb-9ccb-a28e370c3cfe.png)

### Versions
- Plugin version: 1.1.14
- Craft version: 3.6.11.2

**Comment by khalwat** [comment]
I'm not sure how or why you're seeing a Settings page for Cookies, but it does not have a Settings page. My guess is that it didn't get installed properly or such.

I'd ask for help in #nitro or from support@CraftCMS.com as it is more likely related to the local dev environment or install.
