### ISSUE TITLE
Update from 1.1.7 to 1.1.8 breaks.

### ISSUE THREAD

**Issue by RosanaRufer** [nystudio107/craft3-cookies#3]
Hi!

First of all, thank you for this great plugin 😄 .

I am opening an issue because latest update from 1.1.7 to 1.1.8 is breaking when trying to get a secure cookie, and you may be able to help me find the solution faster.

The breaking change is caused by commit `a545eb7d782dbe532f04c81404b47b2f3751b64b` in CookieService, line 139 and below.
Previously, that function does:
`$cookie = Craft::$app->request->cookies->get($name);`
Before the change, it checked if $cookie wasn't empty but after the change it directly tries to access $cookie->value.

This happens when I do `getSecureCookie('cookie_name')` in a view, to check for the cookie value that was set by another app in another subdomain of the same domain.

![jan-31-2018 16-38-16](https://user-images.githubusercontent.com/4906291/35631816-362bdccc-06a5-11e8-9916-61e3a7d7746c.gif)

Shouldn't it check if $cookie is empty first? 
Thanks!

**Comment by khalwat** [comment]
Yes, I think it should.

**Comment by khalwat** [comment]
Fixed in 1.1.9:

https://github.com/nystudio107/craft-cookies/releases/tag/1.1.9

IMPORTANT: the package name has changed. You'll need to update your `composer.json` to "nystudio107/craft-cookies": "^1.0.0"
