### ISSUE TITLE
Field Uids - changed

### ISSUE THREAD

**Issue by rossnorthrup** [nystudio107/craft3-cookies#33]
### Question
I locally added this plugin and after installation, it changed the fieldUids to many volumes and other types.
I was wondering if there would be consequences for pushing this to my production environment. 
Everything seems to work fine, just wondering and trying to prevent making a mess.

**Comment by khalwat** [comment]
This plugin does not do anything that could change your fieldUids. That is probably just a side-effect of using Project Config.

There should not be any consequences to pushing this to other environments.
