### ISSUE TITLE
Default to Craft's defaultCookieDomain setting for domain

### ISSUE THREAD

**Issue by chasegiunta** [nystudio107/craft3-cookies#5]
If `defaultCookieDomain` is set in Craft's config settings, can (or should) that be the default craft-cookies uses, if `DOMAIN` is left blank?

**Comment by khalwat** [comment]
That's probably not a bad idea.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-cookies/commit/2bf05df9a5b14790844a61641cb6417227e309bc
