### ISSUE TITLE
unserialize() expects parameter 2 to be array, boolean given for PHP version >= 7.1.0

### ISSUE THREAD

**Issue by boldenamsterdam** [nystudio107/craft3-cookies#6]
`getSecureCookie` function returns empty value on PHP 7.1.0

Issue is found in "CookiesService" on line 161
`$result = @unserialize(base64_decode($data), false);`

Please change it to
`$result = @unserialize(base64_decode($data), ['allowed_classes' => false]);`

From PHP 7.1.0 onwards `unserialize` function requires strict options naming.
http://php.net/manual/en/function.unserialize.php#121813

I have not tested with PHP 7.0

I would also suggest to remove '@' so debugging of errors would be easier :)

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-cookies/releases/tag/1.1.11
