### ISSUE TITLE
No plugin exists with handle "cookies"

### ISSUE THREAD

**Issue by kellyannmcnamara01** [nystudio107/craft3-cookies#8]
We've been using this plugin for about a week and everything has been fine. An hour ago we are now unable to install the plugin via command line or through the craft plugin store. 

**Problem:** 
Unable to install the plugin

**Error message from the command line:** 
`Nothing to install or update`

**Error message from Craft's plugin store:** 
`Response: {"error":"No plugin exists with the handle \"cookies\"."}`

**Request:** 
Would like to be able to install the plugin again

**Other Notes**
We installed the plugin March 1, 2019. This was after the date that you updated the package name in [this](https://github.com/nystudio107/craft-cookies/issues/3) issue ticket

**Comment by robbue** [comment]
I had the same problem, and in my case the project config (`Craft::$app->getProjectConfig()` used with `./craft install/plugin`) did not return all plugins.

`./craft project-config/rebuild` fixed it.

**Comment by khalwat** [comment]
Yeah probably the plugin just isn't installed somehow.
